### ISSUE TITLE
Do not git pull on first run.

### ISSUE THREAD

**Issue by kylegordon** [linuxserver/docker-sickbeard#8]
The Docker entrypoint script should not be doing a git pull on startup. Docker images should be static precomputed images that are transportable and immutable.

The git pull should be done at the build stage, and then the final product uploaded to Docker hub. With it being done on first run, there is no way to guarantee that the image will work (like I just have, with a DNS failure resulting in a pull failure), and the image is also prone to false starts due to github outages. Once a false start is encountered, the user has no choice but to stop the container, remove the image, and redownload the entire docker image again.

**Comment by sparklyballs** [comment]
While there is an argument for having the git clone being done at the build stage and it may be something that we could look at some stage, it would be for operational reasons that you touch upon in your second paragraph rather than the spurious argument in your opening paragraph

Docker containers by rights should not have process managers and if the service/app stops the container should too, we add a process manager to keep containers up and running for ease of use for our end users. We compromise on "the docker way" in certain areas for usability.
